### ISSUE TITLE
Public announcement

### ISSUE THREAD

**Issue by pnorman** [pnorman/bolder#18]
Draft announcement

-----

# Bolder - Starting a new client-side OpenStreetMap style

I’ve started work on a new client-side style for OpenStreetMap data, and feel it’s reached the point where I can release it to the public. My goal is to make a style that shows a rich selection of the data OSM has, and to make use of most of the colour space, rather than a style designed for overlaying other data on top of.

As a new style, I’ve been able to approach a lot from scratch, looking at avoiding mistakes of previous projects, and using best practices while building on existing work. All the components are open-source, and no assumptions are made about using closed-source software or particular commercial solutions.

![Bolder example image](https://user-images.githubusercontent.com/1190866/39421549-d9062556-4c69-11e8-93f2-6f7031f53540.png)
## Technical overview
The style is rendered with Tangram, which allows for client-side rendering. Server-side rendering [is possible](https://github.com/tangrams/paparazzi) but is a secondary target. Closely coupled with the client-side style is a set of vector tile definitions, handled by Tegola, a vector tile server. It pulls from an osm2pgsql database in the OpenStreetMap Carto schema, with additional data like ocean polygons loaded in by a script.

## Cartographic target
The goal of Bolder is to be a general-purpose style, filling a target similar to OpenStreetMap Carto, while also being a better “default” for people wanting an OSM map. Being a client-side style, it’s easier to turn off classes of features like some POIs if a map with fewer features is needed.

The style should still be useful for mapper feedback, and some ways will become more useful. Vector tiles can associate OSM feature IDs with objects in many cases, helping debugging “where did that label come from”.

## Setup
The style has two arts that are installed, one for the vector tiles, and the other for displaying the client-side style. The documentation for both of them has been tested by users who hadn’t seen it before, so it should be possible to set up for anyone reasonably experienced in style authoring.

## Limitations
As a new project, Bolder has limitations. The biggest limitation is that only a small number of features are rendered, and many things have to be added. I’ve also been doing lots of new stuff with Tegola, and have uncovered [a number of critical bugs](https://github.com/pnorman/bolder/issues/13), most of which should be fixed next Tegola release.

**Comment by kocio-pl** [comment]
As I have commented in the diary entry, It lacks a direct link to this repo in a prominent place.

**Comment by pnorman** [comment]
Link added to entry and mailing list

**Comment by pnorman** [comment]
Reverse links: https://www.openstreetmap.org/user/pnorman/diary/43814 https://lists.openstreetmap.org/pipermail/dev/2018-April/030217.html

**Comment by kocio-pl** [comment]
I think prominent position would be just before image preview, no at the end, since it looks like being part of the last section ("Limitations") and I really needed a moment to find it.
